# cadastro de video
POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "video 01",
    "description": "este é o video 01",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=node

###

# busca de video
PUT http://localhost:3333/videos/748b577c-6b70-4acd-88df-840412251708
Content-type: application/json

{
    "title": "video 02",
    "description": "este é o video 02 ferinha",
    "duration": 180
}

###
DELETE http://localhost:3333/videos/07911eae-6e70-4582-9624-c537ff61a547